# Inputs

In [9]:
# Programa para dividir dos números

num_1 = int(input("Digite el primer número: "))
num_2 = int(input("Digite el segundo número: "))

resultado_division= num_1/num_2

print("El resultado de la operación es: "+ str(resultado_division))

Digite el primer número: 9
Digite el segundo número: 2
El resultado de la operación es: 4.5


# Try-except (Try-catch)

In [16]:
# Sin bloque try-except
edad_years_str= input("Digite su edad en años: ")
edad_years = int(edad_years_str)
edad_meses = edad_years * 12
print("Su edad en meses es: "+ str(edad_meses))


Digite su edad en años: 20
Su edad en meses es: 240


In [17]:
# Con el bloque try-except
# Permite manejar errores sin que el programa se detenga
edad_years_str= input("Digite su edad en años: ")

try:
  edad_years = int(edad_years_str)
  edad_meses = edad_years * 12
  print("Su edad en meses es: "+ str(edad_meses))
except:
  print("Debe digitar un número")

Digite su edad en años: veinte
Debe digitar un número


# Assert

In [22]:
# Es una instrucción que se utiliza para verificar si una condición se cumple.
# Es ideal cuando necesitamos asegurarnos de que los datos tengan un formato determinado o estén en un rango

peso = float(input("Digite su peso en kilogramos: "))
estatura = float(input("Digite su estatura en metros: "))

assert peso > 0, "El peso debe ser mayor a 0"
assert estatura > 0, "La estatura debe ser mayor a 0"

imc = peso / (estatura ** 2)
print("Su IMC es: "+ str(imc))

Digite su peso en kilogramos: 75
Digite su estatura en metros: 1.80
Su IMC es: 23.148148148148145


# List comprehensions

In [29]:
# Crear una lista de los números del 1 al 10 elevados al cuadrado
# [1, 4, 9, 16, 25, 36, ...]

# [expresión for iterable if condición]

numeros_al_cuadrado = [x**2 for x in range(0,11) if x**2 % 2 == 0]

print(numeros_al_cuadrado)

[0, 4, 16, 36, 64, 100]


# Numpy

In [33]:
# Importar Numpy siempre con el alias de np
import numpy as np

### Operaciones matemáticas

In [43]:
x = 26
y = -2

print("\n--- 1. ARITMÉTICA BÁSICA ---")
print("Potencia (np.power()):", np.power(x, 2))
print("Valor absoluto (np.abs()):", np.abs(-x))

print("\n--- 2. EXPONENCIALES Y LOGARITMOS ---")
print("Exponencial (np.exp()):", np.exp(x))
print("Logaritmo natural (np.log()):", np.log(x))
print("Logaritmo base 10 (np.log10()):", np.log10(x))
print("Logaritmo base 2 (np.log2()):", np.log2(x))

print("\n--- 3. REDONDEO Y DECIMALES ---")
print("Redondeo hacia abajo (np.floor()):", np.floor(x))
print("Redondeo hacia arriba (np.ceil()):", np.ceil(x))

print("\n--- 4. TRIGONOMETRÍA ---")
print("Seno (np.sin()):", np.sin(x))
print("Coseno (np.cos()):", np.cos(x))
print("Tangente (np.tan()):", np.tan(x))
print("Arcotangente (np.tan()):", np.atan(x))
print("Grados a radianes (np.deg2rad()):", np.deg2rad(180))
print("Radianes a grados (np.rad2deg()):", np.rad2deg(np.pi))



--- 1. ARITMÉTICA BÁSICA ---
Potencia (np.power()): 676
Valor absoluto (np.abs()): 26

--- 2. EXPONENCIALES Y LOGARITMOS ---
Exponencial (np.exp()): 195729609428.83878
Logaritmo natural (np.log()): 3.258096538021482
Logaritmo base 10 (np.log10()): 1.414973347970818
Logaritmo base 2 (np.log2()): 4.700439718141092

--- 3. REDONDEO Y DECIMALES ---
Redondeo hacia abajo (np.floor()): 26.0
Redondeo hacia arriba (np.ceil()): 26.0

--- 4. TRIGONOMETRÍA ---
Seno (np.sin()): 0.7625584504796027
Coseno (np.cos()): 0.6469193223286404
Tangente (np.tan()): 1.1787535542062797
Arcotangente (np.tan()): 1.5323537367737086
Grados a radianes (np.deg2rad()): 3.141592653589793
Radianes a grados (np.rad2deg()): 180.0


## Matrices

In [56]:
# Forma nativa de python
matriz_manual = [[1,2], [2,4]]
matriz_manual_2 = [[1,2], [2,4]]

# Matriz con numpy
matriz_numpy = np.array([[8,4], [3,5]])

print(type(matriz_manual))
print(type(matriz_numpy))


<class 'list'>
<class 'numpy.ndarray'>


In [54]:
matriz1 = np.array([[8,4], [3,5]])
matriz2= np.array([[2,4], [3,4]])

In [62]:
# Ver el tamaño de una matriz
print(matriz1.shape)

# Ver el número de elementos de una matriz
print(matriz1.size)

# Ver el tamaño en bytes
print(matriz1.nbytes)

(2, 2)
4
32


In [63]:
# Acceder a los elementos de la matriz
print(matriz1)
print(matriz1[0,1])

[[8 4]
 [3 5]]
4


In [64]:
# Acceder a la primera fila de la matriz
print(matriz1)
print(matriz1[0,:])

[[8 4]
 [3 5]]
[8 4]


In [65]:
# Acceder a la primera columna de la matriz
print(matriz1)
print(matriz1[:,0])

[[8 4]
 [3 5]]
[8 3]


In [66]:
# Cambiar la primera fila de la matriz por [0, 0]
matriz1[0,:]=[0,0]

In [68]:
matriz1

array([[0, 0],
       [3, 5]])

In [71]:
# Crear una matriz llena de ceros:
matriz_nula = np.zeros((9,5))
matriz_nula

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [77]:
# Crear una matriz de números aleatorios - Enteros
matriz_ateatorios_ent = np.random.randint(1, 10, (3,3))
matriz_ateatorios_ent

array([[3, 9, 6],
       [3, 4, 2],
       [2, 8, 7]])

In [75]:
# Crear una matriz de números aleatorios - De cero a uno
matriz_ateatorios = np.random.rand(3,3)
matriz_ateatorios

array([[0.55468263, 0.5451155 , 0.37291267],
       [0.48707554, 0.46253858, 0.65754034],
       [0.33407285, 0.43467708, 0.30874414]])

### Operaciones entre matrices

In [80]:
# Transpuesta

print(matriz_ateatorios_ent)
print(matriz_ateatorios_ent.T)

[[3 9 6]
 [3 4 2]
 [2 8 7]]
[[3 3 2]
 [9 4 8]
 [6 2 7]]


In [84]:
# Multiplicación @
matriz_ateatorios_1 = np.random.randint(1, 10, (3,3))
matriz_ateatorios_2 = np.random.randint(1, 10, (3,3))

print(matriz_ateatorios_1)
print(matriz_ateatorios_2)
print(matriz_ateatorios_1*matriz_ateatorios_2)
print(matriz_ateatorios_1@matriz_ateatorios_2)

[[6 9 4]
 [6 2 1]
 [3 2 6]]
[[3 8 6]
 [5 8 2]
 [8 7 7]]
[[18 72 24]
 [30 16  2]
 [24 14 42]]
[[ 95 148  82]
 [ 36  71  47]
 [ 67  82  64]]


In [85]:
# Sacar la inversa de una matriz
print(np.linalg.inv(matriz_ateatorios_1))

[[-0.04694836  0.21596244 -0.00469484]
 [ 0.15492958 -0.11267606 -0.08450704]
 [-0.02816901 -0.07042254  0.1971831 ]]


In [102]:
# Sistema de ecuaciones
# CASO: Resolver un sistema de ecuaciones
# 2x + 3y = 8
#  x -  y = 1

# Matriz A
A = np.array([[2,3],
              [1,-1]])

# Vector B
B = np.array([8,1])

# Solución
x = np.linalg.solve(A, B)
print(x)


[2.2 1.2]


## Operaciones de estadística

In [86]:
# Operaciones estadísticas
datos_estatura= np.random.randint(150, 190, (800,1))

In [92]:
# Media
print(np.mean(datos_estatura))

# Mediana
print(np.median(datos_estatura))

# Desviación estándar
print(np.std(datos_estatura))

# Varianza
print(np.var(datos_estatura))

# Valor mínimo y máximo
print(np.min(datos_estatura))
print(np.max(datos_estatura))

# Percentiles
print(np.percentile(datos_estatura, 80))


169.2825
169.0
11.326857187675671
128.29769375
150
189
181.0


# Scipy

In [97]:
from scipy.stats import skew, kurtosis

# Curtosis
print(kurtosis(datos_estatura))

# Asimetría
print(skew(datos_estatura))

[-1.19087739]
[0.05760192]


In [101]:
# Resolver integrales
from scipy import integrate

def funcion_integral(x):
  return np.log(x)

area_bajo_funcion = integrate.quad(funcion_integral, 0, 70 )
print(area_bajo_funcion)


(227.39466694345512, 2.5245879491759283e-13)


In [104]:
# Optimizar una función
def funcion_optimizar(x):
  return x**2 + 4*x - 9

from scipy import optimize

minimo = optimize.minimize(funcion_optimizar, x0=0)
print(minimo)


  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: -13.0
        x: [-2.000e+00]
      nit: 2
      jac: [ 0.000e+00]
 hess_inv: [[ 5.000e-01]]
     nfev: 6
     njev: 3


In [105]:
funcion_optimizar(-2)

-13